languageCode = "en-us"
title = "pnyv dot sh"
baseURL = "/"
theme = "darktheme"
SectionPagesMenu = "main"

[params]
    description = "a designer's opinionated series of posts."
    show_menu = true
    powered_by = false
    theme_variant = "hack dark"

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about"
    
[[menu.main]]
    name = "Inspiration"
    wight = 4
    identified = "instagram"
    url = "https://instagram.com/pnyvsh"