baseURL = "/"
languageCode = "en-us"
theme = "tim"
[params]
  description = "The creative musings of pnyvsh."
  subtitle = "The Creative Musings of"
  author = "Punya"
  bio = "I'm a UI / UX Designer with a passion for code and copy-editing."
  twitter = "pnyvsh"
  github = "pnyvsh"
  email = "pnyvsh@gmail.com"
 # cv = "/CV.pdf"
title = "The Creative Musings of Punya"
