name = "Tim"
license = "MIT"
licenselink = "https://github.com/adamisntdead/tim/blob/master/LICENSE.md"
description = "A Minimal Hugo Theme Based On Tim Holmans Personal Site"
homepage = "http://example.com/"
tags = ["blog", "minimal", "responsive", "personal", "simple"]
features = ["blog", "responsive"]
min_version = "0.36.1"

[author]
  name = "Adam Kelly"
  homepage = "http://adamisntdead.com"

# If porting an existing theme
[original]
  author = "Tim Holman"
  homepage = "http://tholman.com"
  repo = "https://github.com/tholman/tholman.com"
